//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingCalculator.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieRatingCalculatorEntities : DbContext
    {
        public MovieRatingCalculatorEntities()
            : base("name=MovieRatingCalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MovieParticipantType> MovieParticipantTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<MovieParticipant> MovieParticipants { get; set; }
        public DbSet<Movie> Movies { get; set; }
        public DbSet<ParticipantType> ParticipantTypes { get; set; }
        public DbSet<MovieProductionParticipant> MovieProductionParticipants { get; set; }
        public DbSet<MovieRating> MovieRatings { get; set; }
        public DbSet<UserLoginHistory> UserLoginHistory { get; set; }
    }
}
