//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingCalculator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieProductionParticipant
    {
        public int Id { get; set; }
        public int MovieId { get; set; }
        public int MovieParticipantTypeId { get; set; }
    
        public virtual MovieParticipantType MovieParticipantType { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
