//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingCalculator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public Movie()
        {
            this.Genres = new HashSet<Genre>();
            this.Countries = new HashSet<Country>();
            this.MovieProductionParticipants = new HashSet<MovieProductionParticipant>();
            this.MovieRatings = new HashSet<MovieRating>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string OriginalName { get; set; }
        public short ReleaseYear { get; set; }
        public Nullable<short> Duration { get; set; }
        public string KinopoiskMovieId { get; set; }
        public Nullable<double> KinopoiskMovieRating { get; set; }
        public Nullable<int> KinopoiskNumberUsersRate { get; set; }
        public Nullable<short> ClusterId { get; set; }
    
        public virtual ICollection<Genre> Genres { get; set; }
        public virtual ICollection<Country> Countries { get; set; }
        public virtual ICollection<MovieProductionParticipant> MovieProductionParticipants { get; set; }
        public virtual ICollection<MovieRating> MovieRatings { get; set; }
    }
}
