//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingCalculator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieParticipantType
    {
        public MovieParticipantType()
        {
            this.MovieProductionParticipants = new HashSet<MovieProductionParticipant>();
        }
    
        public int Id { get; set; }
        public int MovieParticipantId { get; set; }
        public int ParticipantTypeId { get; set; }
    
        public virtual MovieParticipant MovieParticipant { get; set; }
        public virtual ParticipantType ParticipantType { get; set; }
        public virtual ICollection<MovieProductionParticipant> MovieProductionParticipants { get; set; }
    }
}
