//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingCalculator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipantType
    {
        public ParticipantType()
        {
            this.MovieParticipantTypes = new HashSet<MovieParticipantType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MovieParticipantType> MovieParticipantTypes { get; set; }
    }
}
