//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRatingCalculator.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.MovieRatings = new HashSet<MovieRating>();
            this.UserLoginHistory = new HashSet<UserLoginHistory>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> ClusterId { get; set; }
    
        public virtual ICollection<MovieRating> MovieRatings { get; set; }
        public virtual ICollection<UserLoginHistory> UserLoginHistory { get; set; }
    }
}
